# Generated by Django 5.2.5 on 2025-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('payment_received', 'Payment Received'), ('recurring_payment', 'Recurring Payment'), ('subscription_payment', 'Subscription Payment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('created_at_time', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('cause', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=100)),
                ('invoice_url', models.URLField()),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
